git checkout -t remotes/origin/01-concept
git checkout -t remotes/origin/02-setup
git checkout -t remotes/origin/03-first-steps
git checkout -t remotes/origin/03-first-steps-basic-layout
git checkout -t remotes/origin/04-finishing-the-menu
git checkout -t remotes/origin/05-the-home-page
git checkout -t remotes/origin/06-meetup-list-single-meetup
git checkout -t remotes/origin/07-vuex-added
git checkout -t remotes/origin/08-create-meetup-basic
git checkout -t remotes/origin/09-date-time-pickers-create-meetup
git checkout -t remotes/origin/10-date-filter
git checkout -t remotes/origin/11-signup
git checkout -t remotes/origin/12-auth-signin-vuex
git checkout -t remotes/origin/13-auth-state-feedback
git checkout -t remotes/origin/14-save-fetch-meetups
git checkout -t remotes/origin/14-save-firebase-check-auth
git checkout -t remotes/origin/15-image-upload
git checkout -t remotes/origin/16-edit-meetups
git checkout -t remotes/origin/17-edit-date-time
git checkout -t remotes/origin/18-register-unregister
git checkout -t remotes/origin/19-fetch-initial-user-state
git checkout -t remotes/origin/20-split-modules
git checkout -t remotes/origin/master-latest-vuetify